#!/usr/bin/env bash

# Set key name, key size, and passphrase
KEY_NAME="school"
KEY_SIZE=4096
PASSPHRASE="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $KEY_SIZE -f $KEY_NAME -N "$PASSPHRASE" <<< y >/dev/null 2>&1

# Confirm key creation
if [ -f "$KEY_NAME" ] && [ -f "$KEY_NAME.pub" ]; then
    echo "RSA key pair created successfully:"
    echo "- Private key: $KEY_NAME"
    echo "- Public key: $KEY_NAME.pub"
else
    echo "Failed to create RSA key pair."
fi
